# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "java"
    open-pull-requests-limit: 3

  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "javascript"
    open-pull-requests-limit: 3

  - package-ecosystem: nuget
    directory: "/csharp"
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "csharp"
    open-pull-requests-limit: 3
