name: Deploy Java Codestyle
on:
  push:
    branches:
      - main
    paths:
      - java/**
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Create build version
        id: create_tag
        uses: mcpierce/github-commit-timestamp-tagger@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Publish package
        run: mvn --batch-mode deploy -Dversion=${{ steps.create_tag.outputs.tag_time }}
        working-directory: ${{ github.workspace }}/java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
